### ISSUE TITLE
Breakpoints in ts-files are being ignored (angular-cli)

### ISSUE THREAD

**Issue by code1line** [Microsoft/vscode-chrome-debug-core#101]
VSCode: 1.6.0-insider
Angular-CLI: 1.0.0-beta.14
URL: http://localhost:4200

Debugging inside Chrome-Dev-Tools works well.
Any ideas?

**Comment by roblourens** [comment]
There are some troubleshooting tips at the bottom of the readme at https://github.com/Microsoft/vscode-chrome-debug - some things you can try to figure out why it can't resolve your sourcemaps. Let me know if it doesn't help.
