### ISSUE TITLE
Support mapping multiple directories with webRoot

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#11]
_From @roblourens on January 20, 2016 0:40_

The `webRoot` property maps a local path to the '/' url path. Webservers can be configured to map multiple directories and we should support this too. See #82.

_Copied from original issue: Microsoft/vscode-chrome-debug#86_

**Comment by nikkwong** [comment]
What's the status on this?

**Comment by roblourens** [comment]
This is actually possible with `pathMapping` now.
