### ISSUE TITLE
Consider swapping sourcemap bias checking order

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#112]
IIRC, it's done this way because in some case the source-map lib will return mappings from a previous line, so if you set a breakpoint at line 5, col 0, you might get the mapping from line 4 instead.

**Comment by roblourens** [comment]
In node-debug, mapFromSource now does LEAST_UPPER_BOUND without falling back on the other one. MapToSource first does GREATEST_LOWER_BOUND, then falls back on least_upper if it doesn't find anything. I should do that too...

**Comment by auchenberg** [comment]
How does other editors and DevTools do this?

**Comment by roblourens** [comment]
It's hard to say since they are usually not using the source-map lib - they end up with the right mapping one way or another.

**Comment by roblourens** [comment]
For posterity, the main impact of this was #417

**Comment by nachocab** [comment]
@roblourens Regarding #19973, I can confirm that it is still not possible to set breakpoints on async/await code

**Comment by Ermish** [comment]
+1 having same issue still

**Comment by roblourens** [comment]
Please open new issues
