### ISSUE TITLE
Enable source maps by default to simplify configuration

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug-core#134]
Given the popularity of sourcemaps we should flip our default setting, so sourcemap support are enabled by default.

**Rational:**
If a source map is present it's most likely needed to resolve paths correctly. Some people don't notice the `sourcemap` config, and end up with a bad first time experience. 

We should therefore flip the setting, and explicitly allow people to disable source maps if needed.

This would simplify the default configs too.

**Comment by roblourens** [comment]
Thoughts on this @weinand? It shouldn't break anyone since you can turn on 'sourceMaps' then debug your code without sourcemaps just fine.

**Comment by weinand** [comment]
If this change affects node2, then we will have to flip the defaults in node1 as well. 
I will investigate what consequences this has in the January milestone.

**Comment by roblourens** [comment]
Right, it should be consistent across. We can change it in chrome-debug to experiment.

**Comment by auchenberg** [comment]
Let's ship this in the Chrome debugger, and evaluate the results.

**Comment by roblourens** [comment]
Enabled for chrome-debug in 2.4.2!

**Comment by auchenberg** [comment]
Yay. Let's see how people are gonna react to this.
