### ISSUE TITLE
Use getPossibleBreakpoints to support column bps, when supported

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#144]
https://chromedevtools.github.io/debugger-protocol-viewer/v8/Debugger/#method-getPossibleBreakpoints

I think when a BP is set at column x, need to call getPossibleBPs for line N, from column 0 to column x, and pick the last one.

If the runtime doesn't support that method, need to set the BP at column 0 (pre-sourcemapping)

**Comment by auchenberg** [comment]
Nicely spotted. This API must be used by Chrome's new inline-breakpoints feature.
