### ISSUE TITLE
Show frame skip status in call stack

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#150]
If a frame is for a skipped file, show `(skipped)` in its name.

**Comment by roblourens** [comment]
@isidorn and @weinand, I'm thinking about how to show that a file is skipped in the call stack. Useful for a few reasons,

- The feature is sort of invisible otherwise
- Something visible will happen when you use the context menu option (I can resend the pause event, so the call stack gets refreshed)
- The context menu must be a toggle because of how the API works, so you need to know the initial state

I can add a tag to the left or right side:
![image](https://cloud.githubusercontent.com/assets/323878/21703541/c84c2e80-d367-11e6-8c4b-2a4527a4d488.png)

The right side might be better since it's the file that's skipped, not the function. But if the frame's Source has a path, then it displays part of the path instead of the source name, so I can't customize it. I guess this is related to #16913. Would it be a breaking change to show the name on the right side, if it's set? Other ideas?

**Comment by isidorn** [comment]
I would start with showing the (skipped) on the right hand side. It belonds next to the file name since the file is skippped and (skipped) is better in a regular than verbatim font.
If that does not work then we can tune it

**Comment by roblourens** [comment]
Sure, so does it make sense to always show the source name when available? Should I open an issue for that?

**Comment by weinand** [comment]
Instead of showing 'skipped' we could try a font variation that does not clutter the UI that much, e.g. showing the module name dimmed and the hover would explain the reason for this).

**Comment by roblourens** [comment]
Then the protocol would have to know about skipFiles?

**Comment by weinand** [comment]
So your approach with the "(skipped)" prefix would just prefix the `name` attribute of the Source object?

**Comment by roblourens** [comment]
Yeah (I would really like the font variation though, it's more similar to what other tools do)

**Comment by roblourens** [comment]
I was debugging some async/await code and was thinking about how much nicer this would look if the module name was dimmed on non-sourcemapped frames

![image](https://cloud.githubusercontent.com/assets/323878/21736066/e9272130-d422-11e6-8c9b-872164b07249.png)

Those frames are skipped with smartStep, not skipFiles, but the two should be marked the same in UI. And was also thinking that I could change the smartStep implementation to be based on the blackbox API, for performance.

**Comment by weinand** [comment]
Even if we are not adding the 'skipFiles' concept to the debug protocol, we could add some abstract attribute to the `StackFrame` or `Source` type.

**Comment by roblourens** [comment]
`hidden` or `dimmed`? Hm, can you think of other situations where this would be useful?

**Comment by weinand** [comment]
@roblourens 'hidden' sounds good. 'dimmed' is too concrete because it is a real visual style.
C++/C# could use 'hidden' to indicate that source is not available.

**Comment by roblourens** [comment]
I'm trying to think of a good synonym for `deemphasized` since it's technically more accurate than `dimmed`.

**Comment by weinand** [comment]
@roblourens I like 'deemphasize' (and the word seems to exist:  http://www.thesaurus.com/browse/de-emphasize but I didn't like any of the listed synonyms).
I've created a protocol change request for this: https://github.com/Microsoft/vscode-debugadapter-node/issues/93

**Comment by weinand** [comment]
@roblourens I've added a `presentationHint` attribute to `Source` and a value  `deemphasize`. It is available in version 1.16.0-pre.1 of the debug protocol.

**Comment by roblourens** [comment]
This looks great! Thanks guys.

![image](https://cloud.githubusercontent.com/assets/323878/21870298/8597beee-d810-11e6-9a42-3ed74fbef8aa.png)

Now I want to use the same UI for code that was smartStep'd over. I'll use the tag `(smartStep)` instead of skipped.

**Comment by roblourens** [comment]
Yes, a stack from async/await with smartStep is infinitely more readable now:

![image](https://cloud.githubusercontent.com/assets/323878/21870982/33425466-d814-11e6-8918-ddfe83ba11e8.png)
