### ISSUE TITLE
Error when trying to install typings

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug-core#16]
```json
➜  vscode-chrome-debug-core git:(master) ✗ typings install --ambient --save es6-collections es6-promise node
typings ERR! message Unable to find "node" ("npm") in the registry. Did you want to try searching another source? Also, if you want contribute these typings, please help us: https://github.com/typings/registry
typings ERR! caused by https://api.typings.org/entries/npm/node/versions/latest responded with 404, expected it to equal 200

typings ERR! cwd /Users/auchenberg/Development/vscode-ios-web-debug/node_modules/vscode-chrome-debug-core
typings ERR! system Darwin 15.0.0
typings ERR! command "/Users/auchenberg/.nvm/versions/node/v5.1.0/bin/node" "/Users/auchenberg/.nvm/versions/node/v5.1.0/bin/typings" "install" "--ambient" "--save" "es6-collections" "es6-promise" "node"
typings ERR! node -v v5.1.0
typings ERR! typings -v 1.0.4

typings ERR! If you need help, you may report this error at:
typings ERR!   <https://github.com/typings/typings/issues>
```

**Comment by jalissia** [comment]
This is because the latest version of typings has changed --ambient to --global
Will need to either specify an exact *older) typings version, or update them and the gulp tasks to the latest version

**Comment by auchenberg** [comment]
I see. I gave up on getting the typings installed. Even a `typings install` seems to install them, but once running the TypeScript compiler it complains.

**Comment by BurtHarris** [comment]
Ran across this issue in a different context.   The current situation with typings vs. tsd is very confusing.

**Comment by roblourens** [comment]
Oh, you don't need to install them manually anymore. Lemme fix up the README

**Comment by roblourens** [comment]
Er, wait yes you still do. I forgot what that was for, if you're trying to add -core as a dependency to a new project. You don't need to do that manually if you're just trying to clone and build -core by itself. But yeah changing the flag to --global should work.
