### ISSUE TITLE
Align node and node2 debug logging parameter names

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#165]
@weinand - Now that 'trace' is documented - https://code.visualstudio.com/docs/editor/node-debugging#_launch-configuration-attributes - should I switch to that instead of 'diagnosticLogging'? Or maybe it doesn't matter since they log totally different things anyway. 'trace' at least is shorter.

I was just thinking of this because I'm going to add the same option to go-debug and need to pick a name. cc @ramya-rao-a

**Comment by roblourens** [comment]
And now this exists: https://github.com/roblourens/vscode-debug-logger

Still deciding what should go into it but it may be useful for other debug adapters in the future. Maybe will move it to Microsoft/

**Comment by weinand** [comment]
@roblourens cool, I'll look into this...

**Comment by weinand** [comment]
@roblourens Why not move the into the 'diagnosticLogging' support into the `vscode-debugadapter` npm module (repo: https://github.com/Microsoft/vscode-debugadapter-node)?

I would start adopting it in node-debug (and would decide what to do with the 'trace' option...).

**Comment by roblourens** [comment]
I was thinking about having a subclass of DebugSession that logs all its traffic, this is basically what I do in vscode-chrome-debug-core. I think it would make sense to have this in vscode-debugadapter-node, so I'll look into that.

I use the name 'trace' in vscode-debug-logger, and 'go' is using that name now.
