### ISSUE TITLE
when hitting a breakpoint gives error "Error processing 'stackTrace': TypeError: Cannot read property 'scriptId' of undefined"

### ISSUE THREAD

**Issue by xsintill** [Microsoft/vscode-chrome-debug-core#167]
I am using vscode 1.9.0 with extension debugger for chrome 2.5.1.

With 1 breakpoint in code running the debugger and hitting this breakpoint gives me the following error

> Error processing "stackTrace": TypeError: Cannot read property 'scriptId' of undefined
>     at ChromeDebugAdapter.displayNameForSourceReference (C:\Users\lneville.LNM\.vscode\extensions\msjsdiag.debugger-for-chrome-2.5.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:1503:50)
>     at ChromeDebugAdapter.<anonymous> (C:\Users\lneville.LNM\.vscode\extensions\msjsdiag.debugger-for-chrome-2.5.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:868:46)
>     at next (<anonymous>)
>     at fulfilled (C:\Users\lneville.LNM\.vscode\extensions\msjsdiag.debugger-for-chrome-2.5.1\node_modules\vscode-chrome-debug-core\out\src\chrome\chromeDebugAdapter.js:7:58)
>     at process._tickCallback (internal/process/next_tick.js:103:7)

I changed return statement code with the commented out code to at least make it work but didn't go in deeper why it returned an empty handle
```
displayNameForSourceReference(sourceReference) {     
        const handle = this._sourceHandles.get(sourceReference);
        return this.displayNameForScriptId(handle.scriptId);
        //return (handle) ? this.displayNameForScriptId(handle.scriptId) : "";
}
```

**Comment by roblourens** [comment]
I fixed one case, here's another. Thanks for the report.
