### ISSUE TITLE
Telemetry: How does eventName get composed?

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug-core#168]
Looking at https://github.com/Microsoft/vscode-chrome-debug-core/blob/b08f533e8b3dfb0b94e6cd36fbb54e73c86e9a53/src/telemetry.ts and how we emit Outputs I'm trying to get an understanding of how we compose the full event name?

Example:
`msjsdiag.chrome/debugstarted`

Where does `msjsdiag.chrome` come from?

**Comment by roblourens** [comment]
I think it might come from vscode - publisher + debug type

**Comment by roblourens** [comment]
I think it must be, I don't see anywhere else that I specify it.

**Comment by auchenberg** [comment]
Yeah, that's what I thought too. Just had a look at `vscode-ios-web-debug` and `vscode-edge-debug` and they are using an too old version of `vscode-chrome-debug-core`, so that's why we don't have telemetry for that.

**Comment by roblourens** [comment]
You'd also need to copy the aiKey in package.json to get telemetry to show up in the same app insights bin, and that should be all you'd have to do to get telemetry, besides updating -core.

**Comment by auchenberg** [comment]
Cool, hereby noted!
