### ISSUE TITLE
Add support of node.js via new v8_inspector in Node core

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug-core#17]
As of https://github.com/nodejs/node/pull/6792, Node will support the `Chrome Debugging Protocol` in it's core via the `v8_inspector` project contributed by Google.

From [reports](https://github.com/nodejs/node/pull/6792#issuecomment-222287868) by @nojvek, the current debugger doesn't work with the Node PR. We should make sure our core debugger works with this potential future version of Node.

**Comment by nojvek** [comment]
I didn't dig deeper but it seems we expect an inspectable page for vscode.
Will debug more and report back on another thread.

Ideally now that the protocol is getting support from different run times,
I would really love to see an effort where this becomes a JavaScript
debugging protocol with extensions that is managed by a working group
similar to w3c.

Happy Memorial Day.

**Comment by auchenberg** [comment]
This feature is current blocked by an invalid `webSocketDebuggerUrl ` returned from the `HTTP /json` endpoint in Node. Issue been opened, https://github.com/nodejs/node/issues/7227.

In addition we need to modify the [target filering logic](https://github.com/Microsoft/vscode-chrome-debug-core/blob/df72f63c8f650296714fb8e489c081eb2d7ace88/src/chrome/chromeConnection.ts#L158) that's currently discarding node targets, which has the `type` : `node`

**Comment by roblourens** [comment]
See https://github.com/microsoft/vscode-node-cdp-debug

**Comment by niieani** [comment]
@roblourens the link you provided is 404.

**Comment by roblourens** [comment]
The repo is private at the moment - we'll open it up sometime soon.
