### ISSUE TITLE
Re-adopt context menu option

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#172]
https://github.com/Microsoft/vscode/issues/19608

**Comment by PauloLeca** [comment]
![dorothyandhusband](https://cloud.githubusercontent.com/assets/23622131/22861778/4053bcb2-f119-11e6-8969-6aee9bec1529.jpg)

**Comment by PauloLeca** [comment]
![por do sol](https://cloud.githubusercontent.com/assets/23622131/22861781/4bb91232-f119-11e6-8d0e-45e12726f577.jpg)
