### ISSUE TITLE
degbuger Unexpected exit

### ISSUE THREAD

**Issue by ydcoming** [Microsoft/vscode-chrome-debug-core#178]
{
    "version": "0.2.0",
    "configurations": [
        {
            "type": "chrome",
            "request": "launch",
            "name": "Launch Chrome against localhost",
            "file":"${workspaceRoot}/bin/index.html",
            "webRoot": "${workspaceRoot}"
        },
        {
            "type": "chrome",
            "request": "attach",
            "name": "Attach to Chrome",
            "port": 9222,
            "webRoot": "${workspaceRoot}"
        }
    ]
}

The cause of the problem is the workspaceRoot containing space; like this :c:/client (1)

**Comment by roblourens** [comment]
This works fine for me. Why do you think that the problem is the workspaceRoot containing a space?

**Comment by ydcoming** [comment]
please rename C:\client (1) 。 debug times  it does not work。

**Comment by roblourens** [comment]
Is this still an issue for you? I still can't repro
