### ISSUE TITLE
Unable to use developer console

### ISSUE THREAD

**Issue by Herethic** [Microsoft/vscode-chrome-debug-core#179]
Hello!

I have a problem: every time I try to open the developer console on the debugging page, my browser closes unexpectedly. On other pages the console opens fine.

_launch.json_
```
{
    "version": "0.1.0",
    "configurations": [
        {
            "name": "Launch localhost",
            "type": "chrome",
            "request": "launch",
            "url": "http://localhost:9000",
            "webRoot": "${workspaceRoot}"
        },
        {
            "name": "Launch index.html",
            "type": "chrome",
            "request": "launch",
            "sourceMaps": true,
            "port": 9000,
            "file": "${workspaceRoot}"
        }
    ]
}
```

**My OS** : Ubuntu 16.04
**My browser** : Google Chrome 55.0.2883.87 (64-bit)
**Visual Studio Code version** : 1.8.0
**Extension version** : 2.5.4

**Comment by auchenberg** [comment]
This happens because Chrome DevTools "overtakes" the connection to Chrome, and kicks VS Code out. When that happens, we close the browser, due to this bug: https://github.com/Microsoft/vscode-chrome-debug/issues/116
