### ISSUE TITLE
Handle groups in debug console

### ISSUE THREAD

**Issue by pkeuter** [Microsoft/vscode-chrome-debug-core#185]
When debugging a React application, Chrome nicely shows groups in the console, whereas vscode does not. It shows the start and end of the group, but they are not actually grouped. This makes the output cluttered and hard to read.

This is the output in Chrome:
![image](https://cloud.githubusercontent.com/assets/433441/23720967/95f631d8-0440-11e7-8dc8-0eddcccb50a1.png)

And this is how vscode shows it:
![image](https://cloud.githubusercontent.com/assets/433441/23721088/fdf91e76-0440-11e7-81b3-7d8ae4882f5d.png)

I think it would be a lot better if vscode shows this like Chrome does. Possibly with the colors that the Chrome console shows.

**Comment by roblourens** [comment]
I could actually put them in a collapsible group now that I can log objects in VSCode. Can't do anything about the colors yet though..

**Comment by roblourens** [comment]
https://github.com/Microsoft/vscode/issues/34981
