### ISSUE TITLE
Error while debugging: Unable to open 'undefined': File not found (/undefined).

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug-core#189]
Not sure why this happens but this error is shown after I click continue after breaking from `Uncaught Exception`

`Unable to open 'undefined': File not found (/undefined).`

![image](https://cloud.githubusercontent.com/assets/1018196/24183997/d5330298-0e88-11e7-86d3-21127b6bd83a.png)

**Comment by roblourens** [comment]
Is it reproducable? Can you send a log?

**Comment by nojvek** [comment]
In python land at the moment, but when I get back to JS, will deffo send a
log.

**Comment by roblourens** [comment]
Handling in https://github.com/Microsoft/vscode/issues/22711
