### ISSUE TITLE
WebAssembly debugging

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#193]
![image](https://cloud.githubusercontent.com/assets/323878/24583257/08a98f2a-16f9-11e7-969c-016bd98b1a28.png)

Probably little or no work required for this.

**Comment by auchenberg** [comment]
Indeed. We should consider spinning out a "Web Assembly" extension with a language server, etc

**Comment by roblourens** [comment]
"Just Works" (tm)

![image](https://cloud.githubusercontent.com/assets/323878/24635664/99cf820c-1889-11e7-847a-c741bc7f79f3.png)

**Comment by auchenberg** [comment]
😱😍😍😍
