### ISSUE TITLE
Path mapping of source files in stack traces not working

### ISSUE THREAD

**Issue by aramando** [Microsoft/vscode-chrome-debug-core#198]
Despite this feature having been implemented and working for some (see #6) I'm still not seeing my Javascript sources' URLs being mapped to their local paths in stack traces in my debug console, which look like this:  

    TypeError: bounds.aspect is not a function
        at Size.resizeToFit (http://localhost:3000/js/Geometry.js:103:31)
        ...

The part of the URL after the protocol is clickable, but results in a file not found error. By the way I'm talking about plain JS files with no sourcemaps. My debug launch config looks like this:
```json
{
    "name": "Launch localhost",
    "type": "chrome",
    "request": "launch",
    "url": "http://localhost:3000",
    "webRoot": "${workspaceRoot}/client"
}
```

Everything is bang up to date:
Code v1.11.1
Debugger for Chrome extension v2.7.3
Chrome version 57.0.2987.133

**Comment by auchenberg** [comment]
@aramando Can you provide some details on how you generate your bundles and sourcemaps?

**Comment by aramando** [comment]
@auchenberg I'm not, my current project is just plain JS files, so my dev source files are the same ones the browser is loading.

**Comment by roblourens** [comment]
Can you hit breakpoints in those files?

**Comment by auchenberg** [comment]
Isn't the issue that you expect the stack trace to be updated from?
```
TypeError: bounds.aspect is not a function
    at Size.resizeToFit (http://localhost:3000/js/Geometry.js:103:31)
    ...
```

to:
```
TypeError: bounds.aspect is not a function
    at Size.resizeToFit ({Your workspaceRoot}/client/js/Geometry.js:103:31)
    ...
```

**Comment by roblourens** [comment]
Right, and it should work without sourcemaps

**Comment by aramando** [comment]
@roblourens Yeah breakpoints and all the usual code-stepping debug features work fine.

@auchenberg Yes, exactly that.

**Comment by roblourens** [comment]
There was an issue like this fixed last month. Please let me know if it still reproes...
