### ISSUE TITLE
No value popup on mouse hover

### ISSUE THREAD

**Issue by FelikZ** [Microsoft/vscode-chrome-debug-core#200]
**Plugin version**: 3.0.1
**VSCode**: 1.11.2

I just established successful setup with google chrome, using the following config:
```json
        {
            "name": "Debug Chrome JS",
            "type": "chrome",
            "request": "launch",
            "port": 9222,
            "userDataDir": "/tmp/chrome-debug",
            "url": "http://localhost/",
            "disableNetworkCache": true,
            "sourceMapPathOverrides": {
                "/source/*": "${workspaceRoot}/frontend/*"
            },
            "webRoot": "${workspaceRoot}/public"
        }
```
So source maps are setup correctly and everything works smooth in terms of code walking.

When it comes to observe values, I can't see those in the _current context_ using a mouse.

See example code below.

If I am stopped on [1] and hover mouse on any variable in this function **except** arguments `(e)` - no value popup is shown (`this` variable used as an example).

Continue moving a mouse in the same state, I hover a mouse on `this` in another function `onKeyDown` [2] then it shows value popup as expected.

```js
    onKeyDown(e) {
        if (e.keyCode == 13 && this.props.onSubmit) {       // [2]
            e.preventDefault();
            return false;
        }
    },

    onKeyUp(e) {
        if (e.keyCode == 13 && this.props.onSubmit) {        // [1]
            e.preventDefault();
            return false;
        }
    }
```
If I add variables to watch, they appear there. The only problem is **variables in current context does not show value popups on mouse hover**.

**Comment by roblourens** [comment]
Sorry for the slow response. We made a few changes in this area this month - first, hover will now work on variables defined outside the current scope, which was not the case before. Second, it was fixed in some TS transpilation cases.

Hope you can try it out in Insiders or vscode 1.15.
