### ISSUE TITLE
Add support for stack traces formatting hints

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-chrome-debug-core#204]
It'd be great if the adapter had support for the stack traces formatting hints: https://github.com/Microsoft/vscode-debugadapter-node/issues/84

e.g.:
stackTrace({"threadId":1,"startFrame":0,"levels":1000,"format":{"parameters":true,"parameterTypes":true,"parameterNames":true,**"line":true,"module":true"**}})

**Comment by roblourens** [comment]
@digeff I had a few questions in the email thread about this, before I can implement this.

**Comment by digeff** [comment]
@roblourens I'm sorry, I missed that e-mail. I've just answered you.
