### ISSUE TITLE
Change the message that we send when we stop on the first line and there is a breakpoint

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-chrome-debug-core#206]
It'd be great if we could change the message that we send when we stop on the first line and there is a breakpoint to: breakpoint rather than: entry to have better support of additional debuggers.

**Comment by roblourens** [comment]
This is working for me in VS Code. I'm not sure why it wouldn't in VS. It should be implemented by https://github.com/Microsoft/vscode-node-debug2/blob/1f17b1cbeaf868a90918ae0ed69293bfe2c70d4c/src/nodeDebugAdapter.ts#L545

Can you try it again and send me a log if it still reproes?

I can't find the original email thread that spawned this. Maybe there were more details there...

**Comment by roblourens** [comment]
Fixed by https://github.com/Microsoft/vscode-node-debug2/commit/154ea7fa313a131e82c6b0f22cbba01c23954f83
