### ISSUE TITLE
Error stack is not sourcemapped

### ISSUE THREAD

**Issue by AskYous** [Microsoft/vscode-chrome-debug-core#212]
I am receiving an error from VSCode saying it cannot find the file when I click on the source of an error in chrome from the VSCode debug console. I am running **Debugger for Chrome version 3.1.2**. I posted a screenshot below. Notice a couple of things:

1. My website is running on localhost:1337. For some reason, VSCode is trying to open the file in /1337/js/components.js. (How did the port get into the source path???)
2. I have source mapping on for my typescript files.
3. The file open is the launch.json file shown in the screenshot. I pointed the `webRoot` folder to my assets folder, yet it seems to completely ignore it.

![image](https://user-images.githubusercontent.com/791996/27094064-c34f472c-501d-11e7-998a-0b8691809e3a.png)

Update: I ran this with `"trace": true`. Here is [vscode-chrome-debug.txt](https://gist.github.com/AskYous/6251cc00b7f63db1a0219bccc2bd8c96).

**Comment by AskYous** [comment]
It might have something to do with angular. The error that Chrome threw was from an [angular component](https://docs.angularjs.org/guide/component) controller.

**Comment by roblourens** [comment]
That error probably showed up when you clicked on the path in the console, right? That's just from the fact that we look for paths very optimistically, and don't support URLs.

But it is a problem that the urls aren't being mapped, since it seems like everything is set up correctly...

**Comment by AskYous** [comment]
Yes. It happened when I clicked on the path in the console.

**Comment by roblourens** [comment]
Can you hit breakpoints in those files?

**Comment by AskYous** [comment]
@roblourens yeah they work just fine. Due to my inability to click on the error location from the command line, I just place a breakpoint in the file that threw the error. Then I click continue from the debugger and tell VSCode to break at the next exception. That's how I find the next exception location that VSCode was trying to map to.

**Comment by roblourens** [comment]
Is the project on github for me to try? Can you share it?

**Comment by AskYous** [comment]
Unfortunately it's private. Let me try to create another project that would produce this error. In the meantime, I have a bit more information that I recorded and put on YouTube. Take a look: https://www.youtube.com/watch?v=Nht4eB2jTzY.

**Comment by AskYous** [comment]
@roblourens Ok, I reproduced the issue using a simple project. I created a repository here with instructions on how to reproduce this error: https://github.com/AskYous/chrome-debug-bug.

**Comment by roblourens** [comment]
Sorry it took so long to get to this. It's just an obvious mistake in hindsight.
