### ISSUE TITLE
Help wanted to launch polymer project

### ISSUE THREAD

**Issue by rajasimon** [Microsoft/vscode-chrome-debug-core#213]
I like to debug or run the polymer project. This is my project structure...
```
project
|__ bower_components
|__ src
|__ index.html
```
And this is my launch configuration...

```
{
    "name": "Launch index.html)",
    "type": "chrome",
    "request": "launch",
    "file": "${workspaceRoot}/index.html",
    "pathMapping":{
        "src": "${workspaceRoot}/src",
        "bower_components": "${workspaceRoot}/bower_components",
    },
    "webRoot": "${workspaceRoot}"
},
```

See this opens chrome with index.html but It fails to load bower_components and src files. Is this configuration is correct or should I need some other settings?

**Comment by roblourens** [comment]
Run `.scripts` (in the console) to see how scripts are resolved to debug it.

**Comment by rajasimon** [comment]
It's log this `› VM32` How this suppose to helps.

**Comment by rajasimon** [comment]
Okay I'm reading here https://github.com/Microsoft/vscode-chrome-debug#the-scripts-command will update the progress tonight

**Comment by rajasimon** [comment]
When I run the debugger it's open the chrome with this url file:///Users/simon/Nightybuild/index.html So I can't use the .scripts to get the help.

**Comment by roblourens** [comment]
What are you trying to accomplish with the pathMapping? That shouldn't be necessary when opening a `file:///`. Also can you be more specific about what the problem is when you say

>  It fails to load bower_components and src files.
