### ISSUE TITLE
Feature request: add support to sourcemap "sections"

### ISSUE THREAD

**Issue by Alphapage** [microsoft/vscode-chrome-debug-core#217]
Hello,
This is related to https://github.com/Microsoft/vscode-node-debug2/issues/117 which I posted to the dependent project 'node2'.
"sections" from the sourcemap specs is not implemented, but SourcemapConsumer supports it.

Do you plan to add this feature ?

Thank you in advance for your answers.

**Comment by roblourens** [comment]
Is there a popular tool that outputs 'sections'?

**Comment by Alphapage** [comment]
I don't know really, but I know I need such a feature in my sourcemap.
I understand the problem is not about the popularity of 'sections', but the implementation which will need to update all dependent projects too.
Because of the new behaviour: the sourcemap should be considered as an array of map, so it will be a major release.

**Comment by roblourens** [comment]
Can you tell me how your sourcemaps are produced, so I can test this? Also, PRs welcome :)

**Comment by Alphapage** [comment]
I made a quick example:
https://github.com/Alphapage/sourcemapsectionsexample
I can't test sections :) for now. I put `debugger;`   in file1.js and file2.js to show the virtual.js resulting file.
I think the project is a working example of how sourcemap including sections should work (maybe offset lines or columns are not correct and need some little adjustment)

**Comment by roblourens** [comment]
Typescript uses these: #52193

**Comment by Kingwl** [comment]
any docs or rfc about this? I'd like to try that

**Comment by roblourens** [comment]
Try what, you want to try fixing it? The problem code is at https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/sourceMaps/sourceMap.ts#L103

We probably just need to reach inside the 'sections' and do the same rewriting of sources that we do for a top-level 'sources' array.

**Comment by wessam526652** [comment]
> Hello,
> This is related to [microsoft/vscode-node-debug2#117](https://github.com/microsoft/vscode-node-debug2/issues/117) which I posted to the dependent project 'node2'.
> "sections" from the sourcemap specs is not implemented, but SourcemapConsumer supports it.
> 
> Do you plan to add this feature ?
> 
> Thank you in advance for your answers.

**Comment by roblourens** [comment]
This project is deprecated, new development taking place in https://github.com/microsoft/vscode-js-debug/issues

**Comment by Kingwl** [comment]
We may could archive this repo to avoid more people find out that?

**Comment by roblourens** [comment]
Yes, we are working on making this more obvious, and soon I will close all issues here and archive the repo. It's a little overdue.

**Comment by Kingwl** [comment]
Just for note: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/archiving-a-github-repository
