### ISSUE TITLE
How do you debug vscode-chrome-debug-core ?

### ISSUE THREAD

**Issue by Alphapage** [Microsoft/vscode-chrome-debug-core#219]
Hello,

I tried the 'launch node-debug2' from launch.json, but only breakpoints from node-debug2 are reached.
I need help to debug core library, not dependent modules. Need to resolve https://github.com/Microsoft/vscode-chrome-debug-core/issues/205 bug.

Thank you in advance for your help.

**Comment by Alphapage** [comment]
Sorry, I was using the wrong port nimber. My mistake.

**Comment by roblourens** [comment]
Also `npm link`, if you haven't found that already.
