### ISSUE TITLE
We should send script unload messages when we refresh a webpage in Chrome

### ISSUE THREAD

**Issue by digeff** [Microsoft/vscode-chrome-debug-core#230]
We should send script unload messages when we refresh a webpage in Chrome

Currently we are not sending the script unload messages, so the scripts get added to the list after we refresh the page

**Comment by roblourens** [comment]
Which event should be sent? The official form is under discussion here: https://github.com/Microsoft/vscode-debugadapter-node/issues/108

**Comment by digeff** [comment]
According to that it seems that the same event but with:
        reason: 'removed';

**Comment by roblourens** [comment]
VS is using a different format currently but I assume you'll switch to the new one when it's finalized - `LoadedSourceEvent` vs `ScriptEvent`

**Comment by digeff** [comment]
@andrewcrawley

**Comment by roblourens** [comment]
I believe we do this now
