### ISSUE TITLE
Discussion: How are you fetching v8 and chromium protocol.json for a specific chrome revision

### ISSUE THREAD

**Issue by nojvek** [Microsoft/vscode-chrome-debug-core#239]
@kdzwinel has a created a prototype extension to extract type info from v8: https://gist.github.com/kdzwinel/5b27649ec5829121e628b79c276a1e52

@roblourens  I wanted to use chrome-remote-debug-protocol to generate crdp interface for latest chromium but wasn't sure how you do your magic to get v8 and chromium protocol.json for a specific chromium version.

@auchenberg Any ideas?

**Comment by auchenberg** [comment]
Node and Chrome now serves the `protocol.json` from `GET /http/json`. You should use this to detect if the API is supported.

**Comment by nojvek** [comment]
😮 😮 😮

Gonna check it out.

**Comment by roblourens** [comment]
`gulp regenerate-crdp`, that's it
