### ISSUE TITLE
Add support for sub-targets via new Targets domain

### ISSUE THREAD

**Issue by auchenberg** [microsoft/vscode-chrome-debug-core#251]
It's expected for Node to land the new CDP Target domain to allow debugging child Node processes, within the next months per https://github.com/nodejs/diagnostics/issues/75#issuecomment-339152681, and Chrome seems to motivated to move the Target domain for discovery.

We should explore how the Target domain works, and how much difference there is between the current HTTP discovery.

- [ ] Can we replace HTTP discovery with the new Target domain
- [ ] Explore how to model sub-targets into threads and new processes within VS Code UX
- [ ] How would Node child processes be surfaced?
- [ ] How would WebWorkers processes be surfaced? 
- [ ] How would ServiceWorkers processes be surfaced?

**Comment by auchenberg** [comment]
Feedback from @joshgav

> My gut is that processes created with Node's child_process and cluster modules should be treated as processes since they spin up new OS processes, and Web service workers should be treated as threads as they (at least appear to) wrap a func/script.

> There are occasional rumblings about supporting Service Worker and true OS threads in Node.js, such as in https://github.com/nodejs/worker (see the tracker there), so if that ever happens you'd mimic the web Service Worker experience for Node.

**Comment by aleclarson** [comment]
This would be super useful for debugging React Native from VS Code. 😄

**Comment by GitStorageOne** [comment]
Node now support workers, so we need a debug tool. Please.

**Comment by MichaelLiss** [comment]
Please add support for workers ( https://nodejs.org/api/worker_threads.html )

**Comment by DemoTenant** [comment]
Please add support to debug workers

**Comment by roblourens** [comment]
This is supported by vscode-js-debug now.
