### ISSUE TITLE
Sourcemap issues when running node and Chrome launch configs simultaneously

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#257]
https://github.com/Microsoft/vscode/issues/28817#issuecomment-346713103

**Comment by hexa00** [comment]
Hi, I just retested with VSCode Version 1.18.1
And Debugger for Chrome 3.5.0

And it now works fine! :)

This issue can be closed, thanks :)

**Comment by roblourens** [comment]
Great! Thanks for trying again.
