### ISSUE TITLE
Possible Typo - Can't find source

### ISSUE THREAD

**Issue by andreujuanc** [Microsoft/vscode-chrome-debug-core#258]
Hello,

Lately I'm getting an error in chromeDebugAdapter.js that Promise.mreject is not defined.

I checked source code (https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L2267) and looks ok.

My file looks like this:
 ```
    // If no expression was passed, we must be getting global completions at a breakpoint
    if (typeof args.frameId !== "number" || !this._frameHandles.get(args.frameId)) {
    return Promise.mreject(errors.stackFrameNotValid());
```

Already fixed locally.

Cheers

**Comment by roblourens** [comment]
Is this in the chrome extension or node?

**Comment by andreujuanc** [comment]
VSCode debugging a cordova project. 

Exception log: https://pastebin.com/LfpdyViA

**Comment by roblourens** [comment]
It's possible that there was a bad publish at some point, not sure how that happened. The latest version of vscode-chrome-debug-core looks fine to me. The Cordova extension will get it whenever they update. Thanks for the heads up!

In any case, you would only get into that block when there's some other error, so something else might have gone wrong...

**Comment by andreujuanc** [comment]
Makes sense.  Since I had few issues with one of the apps I'm developing.

Cheers, thanks for confirming that everything is fine. +1
