### ISSUE TITLE
Add wildcard matching to url config

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug-core#3]
In order to make it simpler to make a generic config for a developers project we should add wildcard url matching

```javascript
{
url: 'http://kenneth.io/*' /// matches all kenneth.io targets
}
```

Possible packages:
- https://github.com/DamonOehlman/wildcard

**Comment by roblourens** [comment]
Thinking about making this more automatic.

If there's no exact match, then `http://kenneth.io` matches the first `kenneth.io` target, whether it's https, or `http://kenneth.io/index.html` or `?something=5`. Basic 'startsWith' match, excluding the protocol. Allowing `http://*.kenneth.io/*/site/*` seems like overkill.

**Comment by roblourens** [comment]
And `kenneth` or `kenneth.io` could match too.

**Comment by roblourens** [comment]
What do you think?

**Comment by auchenberg** [comment]
How about parsing the URLs, and match the `domain` parts and optionally match the `path` part if the configured URL has a path? That way we are striping querystrings, hashes, etc.
