### ISSUE TITLE
Support callstack paging

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#30]
P2, 1 day?
Currently we only show 20 frames but now the framework supports this

**Comment by roblourens** [comment]
I don't think we can actually do this with CDP, since we get all the frames at once in the `Debugger.paused` event. I don't know that it's a problem though.

**Comment by auchenberg** [comment]
@roblourens Any reason for why we can't show all frames? Rendering perf?

**Comment by roblourens** [comment]
Sending info across the wire about lots of frames has bogged down the connection in the past, so we have the option to lazy load them. This might have been more of a problem with the legacy node debug protocol connection, than the connection between the debug adapter and vscode, though.
