### ISSUE TITLE
Include strings for language pack languages in repo

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#309]
So that they can be included in VS, but exclude them from the extensions published in vscode.

cc @rakatyal

**Comment by roblourens** [comment]
@rakatyal Watch out that some languages do not have 100% translation on Transifex. If this is a blocker for VS, we'll have to find another solution.

**Comment by rakatyal** [comment]
@roblourens: Thanks for the heads up. I spoke to Dhanvi and he says this is fine for now and we will reassess it in the future.
