### ISSUE TITLE
totalFrames is different from stackFrames.length

### ISSUE THREAD

**Issue by eyqs** [Microsoft/vscode-chrome-debug-core#340]
https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L1878

Why is this line above the `stackFrames.slice` lines? Is `stackFrames.length` allowed to be different from `totalFrames` in the response?

**Comment by roblourens** [comment]
Yes, totalFrames is the total number of frames, but the adapter can request a certain slice of frames.
