### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#37]
P2, 4 days
The Node adapter is localized and we should be too, especially for our Node adapter.

**Comment by auchenberg** [comment]
What do we need to localize? The error messages?

**Comment by auchenberg** [comment]
What's meant here by localization?

**Comment by roblourens** [comment]
Closed the wrong bug :P

**Comment by roblourens** [comment]
(Translation)

**Comment by auchenberg** [comment]
:)
