### ISSUE TITLE
Node debugger in VS not stopping on breakpoints when project is loaded from a network share

### ISSUE THREAD

**Issue by Shenniey** [Microsoft/vscode-chrome-debug-core#377]
When attempting to debug a Node project in Visual Studio that is loaded from a network share, breakpoints that are set are not bound, and therefore not being hit. 

I believe the error is due to a mismatch in the filepath representation. I've attached one run of the logs below. In the SetBreakpoints method it is looking for a path with two leading backslashes, with directories indicated by backslashes. However when the scripts are loaded, it has a single forward slash in the beginning, and lower directories are also indicated by forward slashes. 

This issue is due to the bug that was filed [here](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/714070). More details are given in the bug link.

Here are the modified log files (I changed some things in case they had private info). 
[dev16 log output from NETWORK SHARE.txt](https://github.com/Microsoft/vscode-chrome-debug-core/files/2550897/dev16.log.output.from.NETWORK.SHARE.txt)

**Comment by roblourens** [comment]
I can repro in vscode

**Comment by roblourens** [comment]
I think I've fixed it.
