### ISSUE TITLE
[loc][Query][vscode_extensions ] Localizability of 0; "out/src/chrome/stoppedEvent.reason.description.entry"

### ISSUE THREAD

**Issue by PDostalek** [Microsoft/vscode-chrome-debug-core#395]
Hi,
please help localization team to answer question from translator.
In case translator is not sure about context/meaning/localizability of string we raise a question to Core team.
Please re-assign back to use in case you are not the right contact person or you can´t assign to a proper person.
Can you help please?
Thanks!

Source:
Paused on frame entry

File Name:
Src\vscode-extensions\vscode-chrome-debug-core.xlf

Resource ID:
0; "out/src/chrome/stoppedEvent.reason.description.entry"

Query:
Does "entry" mean "enter" or "record"? We assumed the former for now, please advise.

**Comment by roblourens** [comment]
"Enter" is the correct interpretation

**Comment by PDostalek** [comment]
Thanks for confirming
