### ISSUE TITLE
Hide [[StableObjectId]] property

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-chrome-debug-core#396]
![image](https://user-images.githubusercontent.com/323878/52733113-c2103800-2f76-11e9-8f34-1b1d5d1812a2.png)

This appears on all scopes in new versions of node and chrome

**Comment by EricCornelson** [comment]
FYI, StableObjectId seems to be removed in the latest Chrome release. See: https://bugs.chromium.org/p/chromium/issues/detail?id=906847

**Comment by roblourens** [comment]
Cool, thanks for pointing that out

**Comment by AhCamargo** [comment]
![image](https://user-images.githubusercontent.com/24438840/65968367-6cbb6500-e439-11e9-9808-6fb567cf1601.png)

This problem came back with version of Google Chrome O Google Chrome 77.0.3865.90

**Comment by roblourens** [comment]
Request handler for the variables request:

https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L1349

At some point in the pipeline returning a list of variables, filter out variables with that name.

What happens if the user actually adds a property with that name...?

**Comment by connor4312** [comment]
If a user adds a property with that name, it appears it'll unfortunately be filtered out. This is the return value from the `variables` command, the `42` value is my user-defined StableObjectId, the `3` is the internal property. However I think this is a sufficiently small edge case.

![image](https://user-images.githubusercontent.com/2230985/66352955-b6aeba00-e915-11e9-862e-80d7ea8f56f1.png)
