### ISSUE TITLE
Support manual override of sourceRoot

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#44]
There's a bug in gulp-sourcemaps < 2.0.0-alpha where it uses `sourceRoot: /source/` by default. This impacts ionic, the ionic2 beta so far, and anyone else using gulp-sourcemaps directly or indirectly. The result is that the file path data in the sourcemap is simply wrong, but the source content is inlined, so it doesn't matter for browser devtools.

In the Ionic case, I honestly can't figure out how to set the sourceRoot from the gulpfile. But it would be really easy to have an option in the launch config to override the sourceRoot globally or for app.bundle.js.

```
"sourceRoot": "${workspaceRoot}"
...
"sourceRoot": "/.." // Looks like nonsense but the proper sourceRoot for the default Ionic2 config is the directory above the webRoot
...
"sourceRoot": {
    "bundle.js.map": "${workspaceRoot}",
    "bundle*": "${workspaceRoot}",
    "somethingElse.js.map": "c:\\project\\src"
}
```

Obviously it's better to fix your build config but this might be nice to get us through this gulp-sourcemaps bug, maybe combined with better logging and optional webRoot.

**Comment by roblourens** [comment]
webpack and meteor also need the sources entries to be modified. And it would be great if this was doable without actually reading the sourcemap file. So it might make sense to have mappings for full paths, not sourceRoot or some other individual property.


These would be applied after doing the 'sourceRoot' + 'sources' operation. After applying the mapping, it would continue to be resolved as usual relative to the sourcemap location or webRoot, if needed.

```
"sourceMappings": {
    "webpack:///*": "*", // Remove webpack://
    "meteor:///<pc emoji>app/*": "*", // Remove meteor:///
    "/source/*": "/*", // Remove source/
    "/dist/app/main.js": "${workspaceRoot}/app/main.js", // Replace exact match to local path
    "main.js": "file:///c:/project/app/main.js", // ok
    "main.js": "http://localhost/main.js", // invalid
}
```

**Comment by roblourens** [comment]
We have the sources, sourceRoot, webRoot, and overrides.

For each source entry:
1. Test it against the overrides. If something was applied, done.
2. If there's a sourceRoot specified in the sourceMap, apply that to the sources entry. Test the result against the overrides. If something was applied, done.
3. Combine it with the computed sourceRoot. 
  - 'computed sourceRoot' meaning code in `sourceMapUtils.getAbsSourceRoot` - produce an absolute local path which is computed from the sourceRoot, webRoot, and the location of the script, as needed.

**Comment by mvidailhet** [comment]
OK, so after running on the same problems trying to debug our Ionic App, I had to add these lines to make it work:
```
"sourceMapPathOverrides": {
    "webpack:///./*":   "${cwd}/*",
    "webpack:///*":     "*",
},
```

It seems that the launch.json uses `cwd` instead of `webRoot`
