### ISSUE TITLE
Replace handwritten Chrome Protocol .d.ts with better system

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#46]
Something like https://github.com/DickvdBrink/chrome-debug-protocol - generating a .d.ts from the package.json. Would have to replace the callbacks with Promises. Would be great if the build fails automatically when the protocol changes.

**Comment by roblourens** [comment]
Or https://github.com/nojvek/chrome-remote-debug-interface!

**Comment by auchenberg** [comment]
What about https://github.com/cyrus-and/chrome-remote-interface? Has support for auto-detecting the support `protocol.json` by doing a HTTP GET `/json/protocol` which is supported by Edge and Node.

**Comment by roblourens** [comment]
Callback-based :/. Also, we have an extra need to implement the server-side, for adapters. I think that's part of @nojvek's motivation to build his own.

**Comment by auchenberg** [comment]
We should keep the notion of adapters, etc our of the core, but simply aim to have a runtime agnostic client that works with any CDP compliant endpoint.

**Comment by roblourens** [comment]
Right, we need something that reads the protocol.json and does the code and typings generation for both sides. This repo would use it for the client side, and another repo would use it for the server side, or both sides.

**Comment by auchenberg** [comment]
I'm a bit unsure of what you mean by client and server side. 

Using a 3rd party library for the actual CDP connection makes sense, while exposing a vscode debugger abstraction for other debuggers in this library makes sense to me.

**Comment by roblourens** [comment]
On one end of the connection, a client is sending `setBreakpoint` and receiving `scriptParsed` events, and on the other, a sever is receving `setBreakpoint` requests and sending `scriptParsed` events, and the code that we should generate for the two is different but closely related.

**Comment by nojvek** [comment]
👍. I think the abstraction could be cleaner. I'll submit a PR.
