### ISSUE TITLE
Improve multi-target debugging for Chrome/Node

### ISSUE THREAD

**Issue by roblourens** [microsoft/vscode-chrome-debug-core#529]
We are actively investigating how to improve the debug experience for web workers, service workers, iframes, node worker threads, etc. This is a master issue for tracking that effort.

**Comment by matteliot** [comment]
any movement?

**Comment by roblourens** [comment]
I will close this, this works in our new debugger implementation: 
https://code.visualstudio.com/updates/v1_43#_new-javascript-debugger
