### ISSUE TITLE
Add more exceptions handling for breakpoints position requests for inline breakpoints

### ISSUE THREAD

**Issue by SounD120** [microsoft/vscode-chrome-debug-core#534]
Hello, I am a maintainer of [vscode-react-native](https://github.com/microsoft/vscode-react-native).
After the VS Code 1.39 update after setting a breakpoint when [debugging Hermes](https://github.com/microsoft/vscode-chrome-debug-core/issues/517) the following message shows up in debug console:
```
Error processing "breakpointLocations": TypeError: Cannot read property 'map' of undefined
    at Breakpoints.<anonymous> (c:\Work\vscode-react-native\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:303:68)
    at Generator.next (<anonymous>)
    at fulfilled (c:\Work\vscode-react-native\node_modules\vscode-chrome-debug-core\out\src\chrome\breakpoints.js:7:58)
```
I looked at the code and found out that `possibleBpResponse` could be `undefined` [at here](https://github.com/microsoft/vscode-chrome-debug-core/blob/31d19232b18071031a9d2489772fb68f1c333e5f/src/chrome/breakpoints.ts#L336) and this might be the cause of this message.
Logs for such case: [chrome-debug-core-session.txt](https://github.com/microsoft/vscode-chrome-debug-core/files/3728274/chrome-debug-core-session.txt)

Also, some Chrome DevTools implementations cannot handle breakpoints location requests correctly and throws errors due to this. Is it possible to disable these requests in some cases?

**Comment by SounD120** [comment]
Hi @roblourens . Could you please also help us to understand why `locations` should be always defined and what weird things React Native can do? [(comment)](https://github.com/microsoft/vscode-chrome-debug-core/issues/517#issuecomment-542411881)
Thank you.
cc @dhanvikapila

**Comment by roblourens** [comment]
Ideally it would match the behavior of chrome and node, and either return an empty array, or fail, in which case vscode will detect that that request is not supported.

**Comment by SounD120** [comment]
Hi @roblourens . Do you have a chance to look at this?

**Comment by roblourens** [comment]
Please report this issue to Hermes. I don't really want to patch a million things for this other runtime. But, if you send a PR to apply a default value here then I will take it.

**Comment by SounD120** [comment]
@roblourens I created a PR #545, please take a look.
