### ISSUE TITLE
Log 1-indexed numbers for debugging sourcemapping code

### ISSUE THREAD

**Issue by lijunle** [Microsoft/vscode-chrome-debug-core#55]
The log shows this:

```
SourceMaps.setBP: Mapped d:\source-file.js:0:0 to d:\bundle.js:965:0
```

I need to `+/-1` when finding my code. Could better to start from `1`.

Related code: [sourceMapTransformer.ts#L75](https://github.com/Microsoft/vscode-chrome-debug-core/blob/ebe75c62f83003e2d831b575e72af86207f4d14d/src/transformers/sourceMapTransformer.ts#L75)

**Comment by lijunle** [comment]
the breakpoint line mapping is right. The problem is, when I am reading the log and going to find out which line it refers to in my code, I need to manually add one. My text editor (vs code) is 1 based, not 0 based.

**Comment by roblourens** [comment]
I see. Yeah it probably makes sense to log 1-indexed numbers there.
