### ISSUE TITLE
Does not work if the url is under https

### ISSUE THREAD

**Issue by ligaz** [Microsoft/vscode-chrome-debug-core#65]
The code is not working correctly if the url protocol is `https` and there are source maps because it cannot download the source map file.

It looks like the problem is the usage of the `http` module in `utils. getURL`. A better alternative is the `fetch` API available via `node-fetch` module.

**Comment by roblourens** [comment]
Thanks for the report, I didn't realize that Node has separate http and https modules.

**Comment by auchenberg** [comment]
https://github.com/Microsoft/vscode-chrome-debug/issues/233

**Comment by jhicken** [comment]
@roblourens So not to be a pain in the butt.... Whats the time frame on this being released. 

![Alt Text](http://big.assets.huffingtonpost.com/Smiling.gif)

I'm really excited about it.

**Comment by roblourens** [comment]
Sorry for the delay, I've been working on vscode 1.9. I'll update it this week though :)

**Comment by jhicken** [comment]
Buahaha. No need to apologize. I'm just grateful for your hard work.
Thanks for the update brother man.
