### ISSUE TITLE
Console messages missing in Canary

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#76]

**Comment by roblourens** [comment]
Switch to `Runtime.consoleAPICalled` (for console APIs) and `Log.entryAdded` (for messages coming from the system, like network errors)

**Comment by auchenberg** [comment]
We need to be backwards compatible here, as the `iOS` and `Edge` debuggers and their protocol adapters still use the `Console` domain.

**Comment by roblourens** [comment]
Fixed in 0.1.19

**Comment by auchenberg** [comment]
So are we now subscribing to the new Logging API or what's the solution?

**Comment by roblourens** [comment]
I have a branch that implements that, but for now I realized they're still sending the text via the old API. Missing info like whether it's an error, but will unblock people for now.
