### ISSUE TITLE
Migrate to new Page.configureOverlay API

### ISSUE THREAD

**Issue by auchenberg** [Microsoft/vscode-chrome-debug-core#79]
`PagesetOverlayMessage ` API has been replaced by `Page.configureOverlay`

https://chromium.googlesource.com/chromium/src/+/02c23fc6d8a185917e1c936fa5a7b9a1c9fa309c%5E%21/#F5

**Comment by roblourens** [comment]
Fixed - https://github.com/Microsoft/vscode-chrome-debug-core/blob/master/src/chrome/chromeDebugAdapter.ts#L302
