### ISSUE TITLE
See only the properties during object's inspection.

### ISSUE THREAD

**Issue by cambieri** [Microsoft/vscode-chrome-debug-core#81]
Hello. Working with the cordova tools debugger, when I inspect an object I also see all the functions and prototypes. Developer MSLaguana told me that their plugin is based on your project, so I ask here for an enhancement, to have a way to only see the properties. Thanks for attention.

**Comment by roblourens** [comment]
This behavior is the same as Chrome devtools', right? Edge's F12 devtools put all the functions of an object under a 'functions' item in the object tree view but I'm not sure I want to copy that behavior. Is there some tool that works the way you expect?

**Comment by cambieri** [comment]
I think that Chrome DevTools works in the way I suggested above: when I inspect an object, they show only the properties, but the functions are under the __proto__ virtual object. Could you try to mimic that behavior? Thanks.

**Comment by roblourens** [comment]
From what I can see, I match Chrome - 
![image](https://cloud.githubusercontent.com/assets/323878/18016913/a44f9b12-6b83-11e6-94c6-35689cedd74f.png)
![image](https://cloud.githubusercontent.com/assets/323878/18016930/b78c6df4-6b83-11e6-8a1d-3c916b47ac75.png)

If there is an object that has its own property that is a function, then that doesn't show up under the `__proto__` property, same as the Chrome DevTools. If there's a difference, please provide a screenshot or code snippet.
