### ISSUE TITLE
Support "noDebug" parameter

### ISSUE THREAD

**Issue by roblourens** [Microsoft/vscode-chrome-debug-core#89]
_From @jan-zajic on September 2, 2016 8:39_

Please add support for nodebug : true parameter (Run mode - launch with ctrl+f5, see https://code.visualstudio.com/docs/editor/debugging#_run-mode).  It was implemented in https://github.com/Microsoft/vscode/issues/2780. This should simple launch Chrome with specified url, without any debuger attaching, so we can use for examples dom inspector, debug css styles or use integrated debugger, which is sometimes better option.

_Copied from original issue: Microsoft/vscode-chrome-debug#220_

**Comment by auchenberg** [comment]
Can we abstract this away in a some generic launch logic, where each debugger `vscode-chrome-debug` and `vscode-edge-dubug` simply provide the runtime executable and arguments?

Thinking this could be relevant for Electron, Edge, iOS, etc.

**Comment by roblourens** [comment]
It might be easier for extensions to launch their own process then just check `if (args.noDebug)` before attaching to it. That's the only difference. Might be able to save them a call to `spawn` but it's not saving much.

**Comment by auchenberg** [comment]
Makes sense, just wanted to make sure we didn't add Chrome specific logic in the core ;)

**Comment by roblourens** [comment]
Moving back to vscode-chrome-debug
