### ISSUE TITLE
Support refreshing the page

### ISSUE THREAD

**Issue by paulirish** [Microsoft/vscode-chrome-debug-core#91]
The other day I really wanted to refresh my page after saving a change in VSCode. Can you make ctrl-R work?

(jam3/devtool does have ctrl-r hooked up to restart the node.js instance, too. I love it.)

**Comment by roblourens** [comment]
Thanks for the suggestion, yes I would really like to support that, although it's not as straightforward as I'd like. Closest I can suggest at the moment is the Restart button, which is cmd+shift+f5. Not quite the same, it will restart the entire browser. It restarts the Node instance in Node debugging too. You could map this to ctrl+r like

```
{ "key": "ctrl+r", "command": "workbench.action.debug.restart",
    "when": "inDebugMode" }
```

**Comment by auchenberg** [comment]
@roblourens What makes this feature complicated?

**Comment by roblourens** [comment]
Just that a debug adapter can't customize the behavior of the restart button at the moment. We talked about this in the past month, and I filed this bug to discuss - Microsoft/vscode#14189

**Comment by auchenberg** [comment]
@roblourens This has landed right? Should we update the README with instructions on how to bind the shortcut?

**Comment by roblourens** [comment]
Oh right, I had duplicate issues.

**Comment by auchenberg** [comment]
@roblourens So mapping this will make the page refresh right?

```
{
   "key": "ctrl+r",
    "command": "workbench.action.debug.restart",
    "when": "inDebugMode"
}
```

**Comment by roblourens** [comment]
Yes

**Comment by auchenberg** [comment]
@paulirish See https://github.com/Microsoft/vscode-chrome-debug/blob/master/README.md#page-refreshing

**Comment by nyakoojo** [comment]
why can't my visual studio code view my html tags and launch my browser.

**Comment by roblourens** [comment]
Can you be more specific? What is the problem?

**Comment by nyakoojo** [comment]
visual studio code is not debugging my html tags even after installation of
the view in default application hope you are understanding me now am using
mac OS X..... How can i go past this. am waiting on thanks Rob.
